version: "3"

services:
  chess-club-api:
    build:
      context: .
    image: chess-club-api
    environment:
      PORT: 4001
      APOLLO_INTROSPECTION: "true"
      APOLLO_PLAYGROUND: "true"
    ports:
      - 4001:4001
    depends_on:
      - db

  db:
    image: postgres:13.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example

# todo: network
