name: Verify

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: joshuaavalon/flyway-action@v1
      with:
        url: jdbc:postgresql://postgres:5432/postgres
        user: postgres
        password: postgres
    - run: npm run verify
